export const prefix = 'LOGIN_'
export const LOGIN_LOADING = prefix + 'LOADING'
export const LOGIN_CHANGE_EMAIL = prefix + 'CHANGE_EMAIL'
export const LOGIN_CHANGE_PASSWORD = prefix + 'CHANGE_PASSWORD'
export const LOGIN_REQUEST_LOGIN = prefix + 'REQUEST_LOGIN'
export const LOGIN_SET_ERROR = prefix + 'SET_ERROR'