export const prefix = 'SESSION_'
export const SESSION_LOADING = prefix + 'LOADING'
export const SESSION_REQUEST_AUTHENTICATION = prefix + 'REQUEST_AUTHENTICATION'
export const SESSION_REQUEST_LOGOUT = prefix + 'REQUEST_LOGOUT'
export const SESSION_SET_ID = prefix + 'SET_ID'
export const SESSION_SET_USER = prefix + 'SET_USER'
export const SESSION_SET_ERROR = prefix + 'SET_ERROR'